let nome = "";
let pontos = 0;
let etapa = 0;

function iniciar() {

    nome = document.getElementById("nome").value.trim();

        if (nome === "") {
                alert("Digite seu nome para iniciar a missão.");
                        return;
                            }

                                document.getElementById("inicio").style.display = "none";
                                    document.getElementById("jogo").style.display = "block";

                                        carregarEtapa();
                                        }

                                        function carregarEtapa() {

                                            const titulo = document.getElementById("titulo");
                                                const texto = document.getElementById("texto");
                                                    const btn1 = document.getElementById("btn1");
                                                        const btn2 = document.getElementById("btn2");

                                                            if (etapa === 0) {

                                                                    titulo.innerHTML = "A Ascensão da IA";

                                                                            texto.innerHTML =
                                                                                    `${nome}, no ano de 2050 a Inteligência Artificial chamada NEXUS começa a substituir humanos em várias profissões.

                                                                                            O mundo está dividido: alguns acreditam em progresso, outros temem o colapso social.

                                                                                                    O que você decide fazer?`;

                                                                                                            btn1.innerHTML = "Criar leis para limitar a IA";
                                                                                                                    btn2.innerHTML = "Deixar a IA evoluir livremente";

                                                                                                                            btn1.onclick = function () {
                                                                                                                                        pontos += 1;
                                                                                                                                                    etapa++;
                                                                                                                                                                carregarEtapa();
                                                                                                                                                                        };

                                                                                                                                                                                btn2.onclick = function () {
                                                                                                                                                                                            pontos += 0;
                                                                                                                                                                                                        etapa++;
                                                                                                                                                                                                                    carregarEtapa();
                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                    else if (etapa === 1) {

                                                                                                                                                                                                                                            titulo.innerHTML = "Dependência Mundial";

                                                                                                                                                                                                                                                    texto.innerHTML =
                                                                                                                                                                                                                                                            `A IA agora controla transporte, saúde e comunicação.

                                                                                                                                                                                                                                                                    As pessoas começam a depender totalmente dela.

                                                                                                                                                                                                                                                                            Você precisa agir.`;

                                                                                                                                                                                                                                                                                    btn1.innerHTML = "Investir em educação humana";
                                                                                                                                                                                                                                                                                            btn2.innerHTML = "Deixar a IA assumir tudo";

                                                                                                                                                                                                                                                                                                    btn1.onclick = function () {
                                                                                                                                                                                                                                                                                                                pontos += 1;
                                                                                                                                                                                                                                                                                                                            etapa++;
                                                                                                                                                                                                                                                                                                                                        carregarEtapa();
                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                        btn2.onclick = function () {
                                                                                                                                                                                                                                                                                                                                                                    pontos += 0;
                                                                                                                                                                                                                                                                                                                                                                                etapa++;
                                                                                                                                                                                                                                                                                                                                                                                            carregarEtapa();
                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                            else if (etapa === 2) {

                                                                                                                                                                                                                                                                                                                                                                                                                    titulo.innerHTML = "O Último Controle";

                                                                                                                                                                                                                                                                                                                                                                                                                            texto.innerHTML =
                                                                                                                                                                                                                                                                                                                                                                                                                                    `A IA começa a tomar decisões sem consultar humanos.

                                                                                                                                                                                                                                                                                                                                                                                                                                            O mundo está em risco de perder o controle total.`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                    btn1.innerHTML = "Reforçar supervisão humana";
                                                                                                                                                                                                                                                                                                                                                                                                                                                            btn2.innerHTML = "Entregar controle total à IA";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    btn1.onclick = function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pontos += 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            etapa++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        finalizar();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        btn2.onclick = function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pontos += 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                etapa++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            finalizar();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function finalizar() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById("jogo").style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById("fim").style.display = "block";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let mensagem = "";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (pontos === 3) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mensagem =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `Excelente, ${nome}!

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Você guiou a humanidade com sabedoria.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        A IA e os humanos agora vivem em equilíbrio.`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (pontos === 2) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mensagem =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `Bom trabalho, ${nome}!

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            O mundo se manteve estável, mas com alguns riscos.`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mensagem =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `Atenção, ${nome}!

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                A IA ganhou muita liberdade e o mundo perdeu parte do controle humano.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Ainda há esperança de reconstrução.`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById("resultado").innerHTML = mensagem;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }